#!/usr/bin/python3



with open('Blacklist1', 'r') as BL1:
    with open('Blacklist', 'w+') as BL:
        for line in BL1:
            BL.write('{} {}\n'.format(line.strip(), 'teenbullshit'))
            
        
